### PR TITLE
fix: add default image for item

### PR DESCRIPTION
**Pull request by karenyavine**
# Description

Adds a default image to the item object

image

MISSING: TESTS

### CODE REVIEW

**Comment by vanessa-cooper** [comment]
Thanks karenyavine, I'll review the changes right away!

**Comment by karenyavine** [comment]
Closes https://github.com/ObelusFamily/Anythink-Market-s5moi/issues/2

**Review by vanessa-cooper — CHANGES_REQUESTED** [review]
Make sure all checks pass, only then you can merge the PR.

**Review by vanessa-cooper — APPROVED** [review]
Excellent job karenyavine! You're now able to merge the PR.

**Pull request merged**
